spring:
  application:
    name: eureka-client-consumer
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true

